default:
  enable_scheduler: false
  schedule_cron: "0 13 * * *"   # daglig 13:00 UTC
  sched_tz: "UTC"
  regions: ["NO1", "NO2", "NO3", "NO4", "NO5"]
  fetch_date_mode: "yesterday"

dev:
  enable_scheduler: true
  schedule_cron: "*/1 * * * *"
